### ISSUE TITLE
Tests are failing in Travis-CI builds and code coverage has declined to 75%

### ISSUE THREAD

**Issue by rcook** [userimpersonate/user_impersonate2#23]
I just fixed a break in the test script which was introduced in commit db61dcfa29cd2c2174bbf43361719b3072f2e9b5 which prevented tests from running properly. In fact, it was preventing tests from running at all and a few failures have been introduced since then (see https://travis-ci.org/userimpersonate/user_impersonate2/jobs/340313007):

```
UserImpersonate::ImpersonateControllerTest#test_configuration_to_use_a_different_model_than_User:
NoMethodError: undefined method `mock' for #<UserImpersonate::ImpersonateControllerTest:0x00000004835c80>
    actionpack (5.1.3) lib/action_dispatch/testing/assertions/routing.rb:175:in `method_missing'
    /home/travis/build/userimpersonate/user_impersonate2/test/functional/impersonate_controller_test.rb:43:in `block in <class:ImpersonateControllerTest>'
```

```
UserImpersonate::ImpersonateControllerTest#test_create_should_require_authentication:
ArgumentError: unknown keyword: use_route
    actionpack (5.1.3) lib/action_controller/test_case.rb:457:in `process'
    devise (4.3.0) lib/devise/test/controller_helpers.rb:33:in `block in process'
    devise (4.3.0) lib/devise/test/controller_helpers.rb:100:in `catch'
    devise (4.3.0) lib/devise/test/controller_helpers.rb:100:in `_catch_warden'
    devise (4.3.0) lib/devise/test/controller_helpers.rb:33:in `process'
    actionpack (5.1.3) lib/action_controller/test_case.rb:392:in `get'
    /home/travis/build/userimpersonate/user_impersonate2/test/functional/impersonate_controller_test.rb:10:in `block in <class:ImpersonateControllerTest>'
```

```
UserImpersonate::ImpersonateControllerTest#test_index_should_require_authentication:
ArgumentError: unknown keyword: use_route
    actionpack (5.1.3) lib/action_controller/test_case.rb:457:in `process'
    devise (4.3.0) lib/devise/test/controller_helpers.rb:33:in `block in process'
    devise (4.3.0) lib/devise/test/controller_helpers.rb:100:in `catch'
    devise (4.3.0) lib/devise/test/controller_helpers.rb:100:in `_catch_warden'
    devise (4.3.0) lib/devise/test/controller_helpers.rb:33:in `process'
    actionpack (5.1.3) lib/action_controller/test_case.rb:392:in `get'
    /home/travis/build/userimpersonate/user_impersonate2/test/functional/impersonate_controller_test.rb:5:in `block in <class:ImpersonateControllerTest>'
```

```
UserImpersonate::ImpersonateControllerTest#test_configuration_uses_default_model_User:
NoMethodError: undefined method `mock' for #<UserImpersonate::ImpersonateControllerTest:0x000000046db240>
    actionpack (5.1.3) lib/action_dispatch/testing/assertions/routing.rb:175:in `method_missing'
    /home/travis/build/userimpersonate/user_impersonate2/test/functional/impersonate_controller_test.rb:20:in `block in <class:ImpersonateControllerTest>'
```

etc.

Furthermore, code coverage has declined from 90% to 75% over the same period.

**Comment by rcook** [comment]
In RSpec `mock` has been removed in favour of `double`.

**Comment by rcook** [comment]
I've fixed up a few things but have commented some tests out since these will require more effort to fix (and I'm short on time at the moment).
